apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  echoedDictionary: 
{{ .Values.TestDictionary | toYaml | indent 4 }}
  newDictionary: 
{{ dict .Values.TestKey .Values.TestValue | toYaml | indent 4 }}
  lookupValue:
    {{ get .Values.TestDictionary .Values.TestKey }}
  keyPresent:
    {{ hasKey .Values.TestDictionary .Values.TestKey }}
  updatedDict:
{{ $updatedDict := deepCopy .Values.TestDictionary }}
{{ $_ := set $updatedDict .Values.TestKey .Values.TestValue }}
{{ $updatedDict | toYaml | indent 4 }}
  removedDict:
{{ $removeDict := deepCopy .Values.TestDictionary }}
{{ $_ := unset $updatedDict .Values.TestKey }}
{{ $updatedDict | toYaml | indent 4 }}
  omittedDict:
{{ omit .Values.TestDictionary .Values.TestKey | toYaml | indent 4 }}
  dictionaryKeys:
{{ keys .Values.EmptyDictionary | sortAlpha | toYaml | indent 4 }}
  dictionaryValues:
{{ values .Values.EmptyDictionary | sortAlpha | toYaml | indent 4 }}
